FROM node:14-alpine

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

COPY package*.json ./

RUN npm install --silent

COPY . .

# Echo NODE_ENV
RUN echo "NODE_ENV is set to $NODE_ENV"

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
