FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --silent

COPY . .

# Application Environment variables
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Echo NODE_ENV
RUN echo "NODE_ENV is set to $NODE_ENV"
RUN echo "NODE_ENV is set to ${NODE_ENV}"

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

