apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_USER: dGVzdHVzZXI= # base64 encoded value of 'testuser'
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3Jk # base64 encoded value of 'testpassword'
  POSTGRES_DB: dGVzdGRi # base64 encoded value of 'testdb'
  #SQLALCHEMY_DATABASE_URI: cG9zdGdyZXNxbC09L3Rlc3R1c2VyOnRlc3RwYXNzd29yZEBwYXNzd29yZC01NDMyL3Rlc3RkYg==
#postgresql://testuser:testpassword@password-5432/testdb
