apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-flask-app
  template:
    metadata:
      labels:
        app: react-flask-app
    spec:
      containers:
        - name: react-flask-app
          image: ecdeise/react-flask-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 443
