apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-upload-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /app/uploads
