apiVersion: v1
kind: Service
metadata:
  name: react-flask-app-service
spec:
  selector:
    app: react-flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort
