name: CI Frontend Build Push to DockerHub Prod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        env:
          NODE_ENV: 'production'
        uses: docker/build-push-action@v4
        with:
          context: ./react_flask_app
          file: ./react_flask_app/Dockerfile.prod
          build-args: |
            "NODE_ENV=production"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-flask-app:latest
