name: CI Frontend Build Push to DockerHub Prod HTTPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Copy SSL/TLS certificates
        run: |
          echo "${{ secrets.SSL_CERT }}" > $GITHUB_WORKSPACE/certificate.crt
          echo "${{ secrets.SSL_KEY }}" > $GITHUB_WORKSPACE/private.key
      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-flask-app:latest \
            --build-arg NODE_ENV=production \
            --build-arg SSL_CERT="$(cat $GITHUB_WORKSPACE/certificate.crt)" \
            --build-arg SSL_KEY="$(cat $GITHUB_WORKSPACE/private.key)" \
            -f $GITHUB_WORKSPACE/react_flask_app/Dockerfile.prod.https \
            --no-cache \
            $GITHUB_WORKSPACE/react_flask_app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-flask-app:latest
