name: Docker Image Build and Deploy to DockerHub

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']

# on:
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Build the Docker image
#         env:
#           MODE: PRODUCTION
#         run: |
#           docker build -f flask_api/Dockerfile.prod -t flask-app:$(date +%s) --build-arg MODE=${MODE} ./flask_api

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        env:
          MODE: PRODUCTION
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(date +"%Y%m%d%H%M%S")
          docker build -f flask_api/Dockerfile.prod -t $DOCKERHUB_USERNAME/flask-app:$IMAGE_TAG --build-arg MODE=${MODE} ./flask_api

      - name: Push the Docker image
        run: |
          IMAGE_TAG=$(date +"%Y%m%d%H%M%S")
          docker push $DOCKERHUB_USERNAME/flask-app:$IMAGE_TAG
