name: Docker Image Build and Deploy to DockerHub

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']

# on:
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Build the Docker image
#         env:
#           MODE: PRODUCTION
#         run: |
#           docker build -f flask_api/Dockerfile.prod -t flask-app:$(date +%s) --build-arg MODE=${MODE} ./flask_api

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          MODE: PRODUCTION
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -f flask_api/Dockerfile.prod -t flask-app:$(date +%s) --build-arg MODE=${MODE} ./flask_api
          docker login --username "${DOCKER_USERNAME}" --password "${DOCKERHUB_TOKEN}"
          docker tag flask-app:$(date +%s) "${DOCKER_USERNAME}/flask-app:$(date +%s)"
          docker push "${DOCKER_USERNAME}/flask-app:$(date +%s)"
