name: Docker Image CI

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          MODE: PRODUCTION
        run: |
          docker build -f flask_api/Dockerfile.prod -t flask-app:$(date +%s) --build-arg MODE=${MODE} ./flask_api
