name: CI Build Push to DockerHub Prod

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  login:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  setup-buildx:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  build-push:
    needs: setup-buildx
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./flask_api
          file: ./flask_api/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
# name: CI Build Push to DockerHub Prod

# # on:
# #   push:
# #     branches:
# #       - 'main'
# on:
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: ./flask_api
#           file: ./flask_api/Dockerfile.prod
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
